export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";

export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANIE_BY_ID = "GET_COMPANIE_BY_ID";

export const GET_EDIT_COMPANY = "GET_EDIT_COMPANY";
