export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANIE_BY_ID = "GET_COMPANIE_BY_ID";

export const GET_CAR = "GET_CAR";
export const GET_CAR_BY_ID = "GET_CAR_BY_ID";

export const GET_DRIVERS = "GET_DRIVERS";
export const GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID";

export const GET_LOCAL = "GET_LOCAL";
export const GET_LOCAL_BY_ID = "GET_LOCAL_BY_ID";

export const GET_PASSENGER = "GET_PASSENGER";
export const GET_PASSENGER_BY_ID = "GET_PASSENGER_BY_ID"

export const GET_REQUESTER = "GET_REQUESTER";
export const GET_REQUESTER_BY_ID = "GET_REQUESTER_BY_ID"

export const GET_BILLS = "GET_BILLS";
export const GET_BILL_BY_ID = "GET_BILL_BY_ID"

// SERVICES
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICE_BY_ID = "GET_SERVICE_BY_ID";
export const NEW_PASSENGER = "NEW_PASSENGER";
export const DEL_PASSENGER = "DEL_PASSENGER";
export const NEW_DRIVER = "NEW_DRIVER";
export const NEW_DESTINY = "NEW_DESTINY";
export const DEL_DESTINY = "DEL_DESTINY";
export const NEW_SERVICE_CAR = "NEW_SERVICE_CAR";
export const NEW_SERVICE_COMPANY = "NEW_SERVICE_COMPANY"
export const NEW_SERVICE_REQUESTER = "NEW_SERVICE_REQUESTER";
export const DEL_SERVICE_REQUESTER = "DEL_SERVICE_REQUESTER"

